[project]
name = "drl-asignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "argparse>=1.4.0",
    "ipython>=8.12.3",
    "numpy>=1.24.4",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
